version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache-ci
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 7700:80
  db:
    container_name: db-ci
    # image: mysql:5.7
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ci_test
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - 3310:3306
  phpmyadmin:
    container_name: phpmyadmin-ci
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: '123'
    depends_on:
        - db